### ISSUE TITLE
Spring Boot 1.3.3 doesn't work

### ISSUE THREAD

**Issue by carlov20** [hdiv/spring-boot-sample-hdiv#1]
When I update the pom to have the Spring Boot Starter Parent 1.3.3.RELEASE the links stop appending the HDIV STATE parameter. I am still able to log in and the hdiv error page still comes up if I try to click a link. I get a:

HDIV_PARAMETER_NOT_EXISTS;/links;_HDIV_STATE_;;;0:0:0:0:0:0:0:1;0:0:0:0:0:0:0:1;tim;

when trying to click on a link.

**Comment by gillarramendi** [comment]
This is a known issue with Spring Boot and Spring Security 4.x.
As a workaround you can downgrade Spring Security to 3.2.x.
Find an example here: https://github.com/hdiv/spring-boot-sample-hdiv/commit/656e585ebb9fd60579348167e30c0162b598a7c0
Thanks!

**Comment by carlov20** [comment]
Thanks for workaround, I was using gradle so I had to use `ext.'spring-security.version' = '3.2.9.RELEASE'` in my gradle build file

**Comment by gillarramendi** [comment]
This problem has been fixed in the latest version. spring-boot-starter-hdiv:1.1.0

**Comment by carlov20** [comment]
Tested it on my project and it works perfectly.

**Comment by gillarramendi** [comment]
Thanks!

**Comment by aaguerra** [comment]
I have erro in trying to add this jar to maven project
 spring-boot-starter-hdiv:1.1.0
